# version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "12345:12345" 
    networks:
      - mynet
    command: ["5555", "100", "1", "2", "3"] 
    volumes:
      - bloom_data:/usr/src/app/data

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server
    networks:
      - mynet
    command: ["server", "5555"]
    stdin_open: true   
    tty: true
    volumes:
      - bloom_data:/usr/src/app/data

  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    networks:
      - mynet

networks:
  mynet:
volumes:
  bloom_data:
