version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "12345:12345" 
    networks:
      - mynet
    command: ["12345", "8", "1", "2"] 

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server
    networks:
      - mynet
    command: >
      bash -c "sleep 2 && python3 tcp_client.py 127.0.0.1 12345"

  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    networks:
      - mynet

networks:
  mynet:
