services:
  blacklist_server:
    build:
      context: ./BlackList_server   # matches your folder exactly (case-sensitive!)
    container_name: blacklist_server
    ports:
      - "12345:12345"
    restart: unless-stopped

  web_server:
    build:
      context: ./Web_server          # matches your folder exactly (case-sensitive!)
    container_name: web_server
    ports:
      - "3000:3000"
    depends_on:
      - blacklist_server           # must match the service name above exactly (lowercase)
    restart: unless-stopped
